### ISSUE TITLE
Transparency slider does not work for a subset of annotations

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#618]
Int he image below, notice how the fill transparency bar is set to zero yet these two annotations are still filled. This happens with many annotations in that slide. 

![image](https://user-images.githubusercontent.com/22067552/54479181-b4a5d200-47f0-11e9-9313-4007da946794.png)

**Comment by kheffah** [comment]
Another example ...

![image](https://user-images.githubusercontent.com/22067552/54479361-64c80a80-47f2-11e9-8edd-86f2c8a1199e.png)

**Comment by kheffah** [comment]
**Update:** We found there was some strange process that was eating up all RAM (a memory leak?) on the server. This may be a low RAM issue. We'll see if this persists once we restart the server.

**Comment by manthey** [comment]
@kheffah Can you confirm that you are using a version from the last few weeks?  There was a bug where if you toggled view and unview fast enough, it would render an annotation twice.  My guess is that this is related, and although I thought the bug was fixed, perhaps not.

**Comment by kheffah** [comment]
@manthey We were not using the latest version, and I was not aware that this was a known bug. When we updated, I couldn't see the issue anymore, so I assume it is fixed. Will re-open if I encounter this again. Thanks!

**Comment by kheffah** [comment]
@manthey Unfortunately, issue seems to still exist even with latest version.

![image](https://user-images.githubusercontent.com/22067552/54714112-990b3600-4b26-11e9-9a61-b1b3b3233d56.png)

**Comment by kheffah** [comment]
This issue was not present in the past. Recently, many annotations started behaving this way and basically not reacting to the fill transparency slide. I think this is bad behavior cause by some recent PR as opposed to a few exceptions/edge cases. Was something major changed in the rendering of annotation filling, or something along these lines, lately?

**Comment by manthey** [comment]
I don't know of a change that should affect this, but, since your seeing it, something changed.

I'm having trouble reproducing this.  Is it possible to take a screen-capture video from loading the slide to when the problem occurs?

**Comment by kheffah** [comment]
Sure, will do.

**Comment by kheffah** [comment]
@manthey There it is. Bug shows at 00:30
[HistomicsTK.zip](https://github.com/DigitalSlideArchive/HistomicsTK/files/2989965/HistomicsTK.zip)

**Comment by kheffah** [comment]
@manthey Here are all the annotations associates with one of the slides that have this issue. Each line is a single annotation document.
[5bff0e57e62914004dc16791.txt](https://github.com/DigitalSlideArchive/HistomicsTK/files/2993688/5bff0e57e62914004dc16791.txt)

**Comment by manthey** [comment]
Thank you -- with your data I can reproduce the problem.  Now I can hunt it down.
